---
title: "sdv_men_variables_coding"
author: "Amedeo"
date: "11/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Laptop path ##

uomo <- readRDS("C:/Users/amedeo/Desktop/R_Projects/stool/stool_vita/New data/uomo_col_changed.rds")

## Desktop path ##
#uomo <- read.csv("C:/Users/UappaSguappa/Desktop/R_Projects/stool_vita/uomo_dataset.csv", sep = "\t")
```

## VARIABILI LEGATE AL FUMO ##

```{r}

levels(uomo$smk_sigari_att) <- c("0","1")
levels(uomo$smk_sigari_pass) <- c("0","1")
levels(uomo$smk_pipa_att) <- c("0","1")
levels(uomo$smk_pipa_pass) <- c("0","1")
levels(uomo$smk_smoke_status) <- c(NA, "1", "0", "2")
levels(uomo$curr_filtro) <- c(NA,"2","0")
levels(uomo$curr_aspirazione) <- c(NA,"0","1","2")
levels(uomo$curr_quit_month) <-c (NA,"1","0")
levels(uomo$ex_ever_stop_before) <- c(NA, "1", "0")
levels(uomo$nev_ever_tried) <- c("0", "1")
levels(uomo$nev_ever_tried_occ) <- c("0","1")
levels(uomo$nev_father_smoke) <- c("0","1")
levels(uomo$nev_mother_smoke) <- c("0","1")
levels(uomo$nev_childhood_smoke_exp) <- c(NA,"2","3","1",NA,"0")
levels(uomo$nev_partner_smoke) <- c(NA, "0", "1", "2", "0")
levels(uomo$nev_partner_presence) <- c(NA,"1")
levels(uomo$nev_other_smoke) <- c("0","1")

```


## VARIABILI LEGATE ALL'ALCOOL ##

```{r}

levels(uomo$alc_ever_alcohol) <- c(NA,"0","1")
levels(uomo$alc_wine) <- c("1","0","2")
levels(uomo$alc_beer) <- c("1","0","2")
levels(uomo$alc_spirits) <- c("1","0","2")


```

## VARIABILI LEGATE ALLE MALATTIE ##

```{r}

levels(uomo$dis_stroke) <- c("0","1")
levels(uomo$dis_angina) <- c("0","1")
levels(uomo$dis_ictus) <- c("0","1")
levels(uomo$dis_high_pressure) <- c("0","1")
levels(uomo$dis_high_col) <- c("0","1")
levels(uomo$dis_high_col_meds) <- c("0","1")
levels(uomo$dis_diabetes) <- c("0","1")
levels(uomo$dis_diabetes_meds) <- c("0","1")
levels(uomo$dis_liver_calc) <- c("0","1")
levels(uomo$dis_gallbladder_removed) <- c("0","1")
levels(uomo$dis_kidney_calc) <- c("0","1")
levels(uomo$dis_kidney_calc_meds) <- c("0","1")
levels(uomo$dis_intestin_polyps) <- c("0","1")
levels(uomo$dis_tumors) <- c("0","1")
levels(uomo$dis_ulcer) <- c("0","1")
levels(uomo$dis_ulcer_meds) <- c("0","1")
levels(uomo$dis_ulcer_surg) <- c("0","1")

```


## VARIABILI STORIA RIPRODUTTIVA ##

```{r}

levels(uomo$rep_partner_pregnant) <- c("0","1")
levels(uomo$rep_alive_childs) <- c(NA,"0","1")

```

## CODING BMI ED ETA ##

```{r}

uomo$age_cat <- with(uomo, cases("_40"= Age<40,
                                 "40_60"= Age>=40 & Age<60,
                                 "60_"= Age>=60))

uomo <- moveMe(uomo, c("age_cat"), "after", "Age")

                                 
uomo$bmi_cat <- with(uomo, cases("1" = bmi<18.5,
                                 "0" = bmi>=18.5 & bmi<25,
                                 "2" = bmi>=25 & bmi<30,
                                 "3" = bmi>=30))

uomo <- moveMe(uomo, c("bmi_cat"), "after", "bmi")

```


## SALVATAGGIO NUOVO DATASET UOMINI ##

```{r}
saveRDS(uomo, "C:/Users/amedeo/Desktop/R_Projects/stool/stool_vita/New data/uomo_var_coded.rds")
```

